---
abstract: 'a simple factory class for DBI database handle'
author:
  - 'Bahootyper, C<< <bahootyper at gmail.com> >>'
  - 'Bahootyper <bahootyper@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::Exception: 0
  Test::More: 0
  YAML::XS: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Factory
no_index:
  directory:
    - inc
    - t
requires:
  Config::Any: 0
  DBI: 0
  File::Spec: 0
  Moose: 0
  Scalar::Util: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
